// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-T1n1yZjdgKr7c0KfQrnlmM8nIYoNCMU',
    appId: '1:452965430504:web:790ebfc4da2d8bc40d855d',
    messagingSenderId: '452965430504',
    projectId: 'empmanagment-127eb',
    authDomain: 'empmanagment-127eb.firebaseapp.com',
    storageBucket: 'empmanagment-127eb.firebasestorage.app',
    measurementId: 'G-V6PKQB3CZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAYrKXcxAyAezkBE4R2gqj996izbSjCNo',
    appId: '1:452965430504:android:c9e6ededd707cfe00d855d',
    messagingSenderId: '452965430504',
    projectId: 'empmanagment-127eb',
    storageBucket: 'empmanagment-127eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy-UObo5JLiX-Vjrt_-_Ed8PKa2H_wvAY',
    appId: '1:452965430504:ios:91b44fdd3f3527b40d855d',
    messagingSenderId: '452965430504',
    projectId: 'empmanagment-127eb',
    storageBucket: 'empmanagment-127eb.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy-UObo5JLiX-Vjrt_-_Ed8PKa2H_wvAY',
    appId: '1:452965430504:ios:91b44fdd3f3527b40d855d',
    messagingSenderId: '452965430504',
    projectId: 'empmanagment-127eb',
    storageBucket: 'empmanagment-127eb.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-T1n1yZjdgKr7c0KfQrnlmM8nIYoNCMU',
    appId: '1:452965430504:web:ca2b972ed05a09f80d855d',
    messagingSenderId: '452965430504',
    projectId: 'empmanagment-127eb',
    authDomain: 'empmanagment-127eb.firebaseapp.com',
    storageBucket: 'empmanagment-127eb.firebasestorage.app',
    measurementId: 'G-L4G6K58QK8',
  );
}
